'use client';

import { useEffect, useState } from 'react';
import Header from '../components/header/Header';
import InterestsSelector from '../components/interests/InterestsSelector';

const CONTACT_TYPE_OPTIONS = [
  { value: 'EMAIL', label: 'Email', placeholder: 'you@example.com' },
  { value: 'PHONE', label: 'Phone', placeholder: '+1 555 123 4567' },
  { value: 'DISCORD', label: 'Discord', placeholder: '@username' },
  { value: 'OTHER', label: 'Other', placeholder: 'Contact handle or URL' },
];

export default function SignUpPage() {
  const [username, setUsername] = useState('');
  const [email,    setEmail]    = useState('');
  const [password, setPassword] = useState('');
  const [confirm,  setConfirm]  = useState('');
  const [generatedCredentials, setGeneratedCredentials] = useState({
    username: '',
    password: '',
  });
  const [autoGenerated, setAutoGenerated] = useState(true);
  const [selectedInterests, setSelectedInterests] = useState([]);
  const [contactMethods, setContactMethods] = useState([]);
  const [loading,  setLoading]  = useState(false);
  const [error,    setError]    = useState('');
  const [msg,      setMsg]      = useState('');

  useEffect(() => {
    const randomToken = () =>
      Math.random().toString(36).slice(2, 8);
    const generatedUsername = `user_${randomToken()}`;
    const generatedPassword = `${randomToken()}${randomToken()}!`;

    setGeneratedCredentials({
      username: generatedUsername,
      password: generatedPassword,
    });
    setUsername(generatedUsername);
    setPassword(generatedPassword);
    setConfirm(generatedPassword);
    setAutoGenerated(true);
  }, []);

  const handleUsernameFocus = () => {
    if (!autoGenerated) return;
    setUsername('');
    setPassword('');
    setConfirm('');
    setAutoGenerated(false);
  };

  const handleUsernameChange = (value) => {
    setUsername(value);
    if (
      autoGenerated &&
      value !== generatedCredentials.username
    ) {
      setAutoGenerated(false);
    }
  };

  const handlePasswordChange = (value) => {
    setPassword(value);
    if (
      autoGenerated &&
      value !== generatedCredentials.password
    ) {
      setAutoGenerated(false);
    }
  };

  const handleConfirmChange = (value) => {
    setConfirm(value);
    if (
      autoGenerated &&
      value !== generatedCredentials.password
    ) {
      setAutoGenerated(false);
    }
  };

  const showGeneratedNotice =
    autoGenerated &&
    username === generatedCredentials.username &&
    password === generatedCredentials.password &&
    confirm === generatedCredentials.password;

  const addContactMethod = () => {
    setContactMethods((prev) => {
      const hasPreferred = prev.some((method) => method.preferred);
      return [
        ...prev,
        {
          localId: `local-${Date.now()}-${Math.random().toString(16).slice(2)}`,
          type: 'EMAIL',
          value: '',
          label: '',
          preferred: !hasPreferred,
          visible: true,
        },
      ];
    });
  };

  const updateContactMethod = (index, field, value) => {
    setContactMethods((prev) =>
      prev.map((method, idx) =>
        idx === index ? { ...method, [field]: value } : method
      )
    );
  };

  const setPreferredContact = (index) => {
    setContactMethods((prev) =>
      prev.map((method, idx) => ({
        ...method,
        preferred: idx === index,
      }))
    );
  };

  const removeContactMethod = (index) => {
    setContactMethods((prev) => prev.filter((_, idx) => idx !== index));
  };

  async function onSubmit(e) {
    e.preventDefault();
    setError('');
    setMsg('');

    // validation
    if (!username || !email || !password || !confirm) {
      setError('Fill all fields');
      return;
    }
    if (password.length < 8) {
      setError('Password must be at least 8 characters');
      return;
    }
    if (password !== confirm) {
      setError('Passwords do not match');
      return;
    }

    setLoading(true);

    try {
      const res = await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username,
          email,
          password,
          interests: selectedInterests,
          contactMethods,
        }),
      });

      const data = await res.json();

      // handle server error
      if (!res.ok) {
        setError(data.error || 'Signup failed');
        return;
      }

      // success
      setMsg('Account created');
      setTimeout(() => {
        window.location.href = '/login';
      }, 800);

    } catch (err) {
      setError('Network error');
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <Header />

      <main className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-4xl font-bold text-center mb-10">Create Account</h1>

        <form onSubmit={onSubmit} className="space-y-6">
          <div>
            <label className="block text-sm mb-1">Username</label>
            <input
              value={username}
              onChange={(e)=>handleUsernameChange(e.target.value)}
              onFocus={handleUsernameFocus}
              className="w-full rounded border px-3 py-2"
              placeholder="yourname"
            />
          </div>

          <div>
            <label className="block text-sm mb-1">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e)=>setEmail(e.target.value)}
              className="w-full rounded border px-3 py-2"
              placeholder="you@example.com"
            />
          </div>

          <div>
            <label className="block text-sm mb-1">Password</label>
            <input
              type="password"
              value={password}
              onChange={(e)=>handlePasswordChange(e.target.value)}
              className="w-full rounded border px-3 py-2"
              placeholder="Min. 8 characters"
            />
          </div>

          <div>
            <label className="block text-sm mb-1">Confirm Password</label>
            <input
              type="password"
              value={confirm}
              onChange={(e)=>handleConfirmChange(e.target.value)}
              className="w-full rounded border px-3 py-2"
              placeholder="Match password"
            />
          </div>

          {showGeneratedNotice && (
            <p className="text-xs text-amber-700 bg-amber-50 border border-amber-200 rounded px-3 py-2">
              A strong password was generated for you. Make sure you save it in a password manager.
            </p>
          )}

          <InterestsSelector
            selectedInterests={selectedInterests}
            setSelectedInterests={setSelectedInterests}
            title="Interests (Optional)"
            description="These are used in Friend Finder to match you with other students."
            helperText="Click to add or remove interests:"
            defaultOpen
          />

          <section className="border border-gray-200 rounded-lg p-4 bg-white shadow-sm">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-black">
                  Contact Methods (Optional)
                </h2>
                <p className="text-xs text-gray-600">
                  You can update this later in your account settings.
                </p>
              </div>
              <button
                type="button"
                onClick={addContactMethod}
                className="rounded bg-green-800 text-white px-3 py-1 text-sm font-semibold hover:bg-green-700"
              >
                Add Method
              </button>
            </div>

            {contactMethods.length === 0 && (
              <p className="mt-3 text-xs text-gray-500">
                No contact methods added yet.
              </p>
            )}

            <div className="mt-3 space-y-3">
              {contactMethods.map((method, index) => {
                const option = CONTACT_TYPE_OPTIONS.find(
                  (opt) => opt.value === method.type
                );
                return (
                  <div
                    key={method.localId || index}
                    className="rounded border border-gray-200 p-3 bg-neutral-50"
                  >
                    <div className="grid grid-cols-1 md:grid-cols-5 gap-3 items-center">
                      <div className="md:col-span-1">
                        <label className="block text-xs text-gray-600 mb-1">
                          Type
                        </label>
                        <select
                          value={method.type || 'EMAIL'}
                          onChange={(e) =>
                            updateContactMethod(index, 'type', e.target.value)
                          }
                          className="w-full rounded border px-2 py-2 text-sm"
                        >
                          {CONTACT_TYPE_OPTIONS.map((opt) => (
                            <option key={opt.value} value={opt.value}>
                              {opt.label}
                            </option>
                          ))}
                        </select>
                      </div>

                      <div className="md:col-span-2">
                        <label className="block text-xs text-gray-600 mb-1">
                          Value
                        </label>
                        <input
                          value={method.value || ''}
                          onChange={(e) =>
                            updateContactMethod(index, 'value', e.target.value)
                          }
                          className="w-full rounded border px-2 py-2 text-sm"
                          placeholder={option?.placeholder}
                        />
                      </div>

                      {method.type === 'OTHER' && (
                        <div className="md:col-span-2">
                          <label className="block text-xs text-gray-600 mb-1">
                            Label
                          </label>
                          <input
                            value={method.label || ''}
                            onChange={(e) =>
                              updateContactMethod(index, 'label', e.target.value)
                            }
                            className="w-full rounded border px-2 py-2 text-sm"
                            placeholder="Telegram, Signal, etc."
                          />
                        </div>
                      )}

                      <div className="md:col-span-5 flex flex-wrap items-center gap-4">
                        <label className="text-xs text-gray-700 flex items-center gap-2">
                          <input
                            type="radio"
                            name="preferredContactSignup"
                            checked={Boolean(method.preferred)}
                            onChange={() => setPreferredContact(index)}
                          />
                          Preferred
                        </label>
                        <label className="text-xs text-gray-700 flex items-center gap-2">
                          <input
                            type="checkbox"
                            checked={method.visible !== false}
                            onChange={(e) =>
                              updateContactMethod(index, 'visible', e.target.checked)
                            }
                          />
                          Visible to others
                        </label>
                        <button
                          type="button"
                          onClick={() => removeContactMethod(index)}
                          className="text-xs text-red-600 underline"
                        >
                          Remove
                        </button>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>

          {error && <p className="text-red-600 text-sm">{error}</p>}
          {msg &&   <p className="text-green-700 text-sm">{msg}</p>}

          <button
            type="submit"
            disabled={loading}
            className="w-full rounded bg-green-800 text-white py-2 font-semibold disabled:opacity-60"
          >
            {loading ? 'Creating…' : 'Sign Up'}
          </button>

          <div className="text-center text-sm mt-2">
            <a href="/login" className="underline">Already have an account?</a>
          </div>
        </form>
      </main>
    </>
  );
}
